const profileLinks = [
  {
    label: "GitHub",
    href: "https://github.com/JoeKooler",
  },
  {
    label: "Twenty Ideas Mini Project",
    href: "https://github.com/JoeKooler/twenty-ideas-mini-project",
  },
  {
    label: "Coding Repo",
    href: "https://github.com/JoeKooler/coding-joekooler",
  },
  {
    label: "LinkedIn",
    href: "https://www.linkedin.com/in/chitsanupong-klaithin-729b97162/",
  },
];

export default function ProfileHighlight() {
  return (
    <section className="mt-10 grid gap-6 rounded-4xl border border-black/5 bg-(--surface) p-6 shadow-card lg:grid-cols-[1.1fr_1fr]">
      <div className="space-y-3">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-accent">
          Joe Highlight
        </p>
        <h2 className="text-2xl font-semibold text-foreground">
          Chitsanupong Klaithin (Joe) • Chiang Mai, Thailand
        </h2>
        <p className="text-sm leading-6 text-muted">
          This page is generated by AI and supervised by Joe. Email:
          chitsanupongklaithin@gmail.com · Phone: +66 909678306.
        </p>
        <p className="text-xs leading-6 text-muted">
          Languages: Thai (Native), English (Fluent), Korean (Basic). Main stack:
          React, Next.js, TypeScript, Node, AWS, Postgres, Unity C#.
        </p>
        <p className="text-xs leading-6 text-muted">
          Ps. I would normally not extract things those are not used more than
          twice but for the project demonstration purpose, I made an exception
          here.
        </p>
        <p className="text-xs leading-6 text-muted">
          Ps_2. That 5 minutes demo video was too short to explain everything.
          If you have any questions, feel free to reach out to me via LinkedIn.
        </p>
      </div>
      <div className="grid gap-3 sm:grid-cols-2">
        {profileLinks.map((link) => (
          <a
            key={link.href}
            className="flex items-center justify-between rounded-2xl border border-black/5 bg-(--surface) px-4 py-3 text-sm font-semibold text-foreground shadow-card transition hover:-translate-y-0.5"
            href={link.href}
            target="_blank"
            rel="noreferrer"
          >
            <span>{link.label}</span>
            <span className="text-xs text-muted">Visit</span>
          </a>
        ))}
      </div>
    </section>
  );
}
