export default function SiteFooter() {
  return (
    <footer className="mt-16 grid gap-6 border-t border-black/10 pt-8 text-sm text-muted md:grid-cols-[1.2fr_1fr] md:items-center">
      <div className="space-y-3">
        <p>© 2026 JoeKooler. All rights reserved.</p>
        <p className="text-xs">This page is generated by AI and supervised by Joe.</p>
      </div>
      <div className="text-xs text-muted">
        CodeWars 5 kyu · Frontend Mentor · Thai/English/Korean
      </div>
    </footer>
  );
}
